services:
  runner:
    build:
      context: ./DockerImage
      dockerfile: Dockerfile
      args:
        - INNER_CIRCLE_CLOUD_PATH_TO_KUBECONFIG=$INNER_CIRCLE_CLOUD_PATH_TO_KUBECONFIG
        - INNER_CIRCLE_CLOUD_PATH_TO_SSH=$INNER_CIRCLE_CLOUD_PATH_TO_SSH
    restart: unless-stopped
    env_file: .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    deploy:
      mode: replicated
      replicas: 8
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
    group_add:
      # Run echo DOCKER_GID=$(stat -c '%g' /var/run/docker.sock) >> .env in the host
      - "${DOCKER_GID}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/inner-circle:/var/log/inner-circle
      - /home/runner/actions-runner/_work:/home/runner/actions-runner/_work
